### ISSUE TITLE
Add YAML/JSON Schema

### ISSUE THREAD

**Issue by tsukinoko-kun** [typst/hayagriva#206] opened 2024-08-31 17:09 UTC
Schema would be useful. It would be used like here for GitHub Actions:  
https://github.com/tsukinoko-kun/codehere/blob/main/.github/workflows/release.yml

```yaml
# yaml-language-server: https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: goreleaser

on:
  create:
    tags:
      - "**"
```

This improves discoverability of features and reduces silly spelling issues.

**Comment by reknih** [comment] 2024-10-10 14:48
Duplicate of #33

**Closed by reknih** 2024-10-10 14:48 UTC
