### ISSUE TITLE
export to bibtex

### ISSUE THREAD

**Issue by wuyoli** [typst/hayagriva#68] opened 2023-10-30 23:21 UTC
Does a exporter tool for export to bibtex already exist? (preferably a cli program) I would like to use this with org-roam-bibtex in emacs. The export to bibtex would be needed because org-roam-bibtex only supports bibtex.

**Comment by Enivex** [comment] 2023-11-05 12:52
You would probably be better served by simply keeping your bibliography as bibtex instead of converting back and forth

**Comment by yochem** [comment] 2023-12-01 07:53
`$ hayagriva refs.yml references --format bibtex > references.bib`

**Comment by reknih** [comment] 2024-10-10 14:12
Duplicate of #171

**Closed by reknih** 2024-10-10 14:12 UTC
